config/routes.rb
Rails.application.routes.draw do
  root 'avengers#index'
  resources :avengers, only: [:index, :show, :create, :new]
  resources :aliases, only: [:show]

end

app/models/alias.rb
class Alias < ActiveRecord::Base
  has_many :monikers
  has_many :avengers, through: :monikers
end

app/models/avenger.rb
class Avenger < ActiveRecord::Base
  has_many :monikers
  has_many :aliases, through: :monikers

  paginates_per 24

  def alias_list
    aliases.map(&:name)
  end

  def alias_list=(comma_separated_aliases)
    these_aliases = comma_separated_aliases.split(",").map(&:strip)
    aliases.destroy_all
    these_aliases.each do |a|
      aliases << Alias.find_or_initialize_by(name: a)
    end
  end
end

app/models/moniker.rb
class Moniker < ActiveRecord::Base
  belongs_to :alias
  belongs_to :avenger
end

app/controllers/aliases_controller.rb
class AliasesController < ApplicationController

  def show
    @alias = Alias.find(params[:id])
    @avengers = @alias.avengers
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/avengers_controller.rb
class AvengersController < ApplicationController

  def index
    @avengers = Avenger.order(year: :asc).page(params[:page])
  end

  def show
    @avenger = Avenger.find(params[:id])
  end

  def new
    @avenger = Avenger.new
  end

  private

  def avenger_params
    params.require(:avenger).permit(:name, :alias_list, :gender)
  end

end

app/helpers/aliases_helper.rb
module AliasesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avengers_helper.rb
module AvengersHelper

  def aliases_links(avenger)
    if avenger.aliases.any?
      avenger.aliases.map{|a| link_to a.name, a}.to_sentence
    else
      "None"
    end
  end

end

app/views/aliases/show.html.erb
<h1><%= @alias.name %></h1>

<ul class="list-unstyled">
  <% @avengers.each do |avenge| %>
    <li><%= link_to avenge.name, avenge %></li>
  <% end %>
</ul>

app/views/avengers/index.html.erb
<h1>Avengers all-time roster</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Aliases</th>
    <th>Gender</th>
    <th>Year Introduced</th>
    <th>Status</th>
  </tr>
<% @avengers.each do |avenge| %>
  <tr>
    <td><strong><%= link_to avenge.name, avenge %></strong></td>
    <td><%= aliases_links(avenge).html_safe %></td>
    <td><%= avenge.gender %></td>
    <td><%= avenge.year %></td>
    <td class="<%= avenge.alive? ? "bg-success" : "bg-danger" %>"><%= avenge.alive? ? "Alive" : "Deceased" %></td>
  </tr>
<% end %>
</table>

<%= paginate @avengers %>

app/views/avengers/new.html.erb
<h1>Add a new Avenger</h1>
<%= simple_form_for @avenger do |f| %>
  <%= f.input :name %>
  <%= f.input :gender %>
  <%= f.input :alias_list, label: "Aliases", hint: "Comma separated" %>
  <%= f.submit "Assemble!", class: 'btn btn-primary btn-large' %>
<% end %>

app/views/avengers/show.html.erb
<h1><%= @avenger.name %></h1>

<p><strong>Aliases:</strong> <%= aliases_links(@avenger).html_safe %></p>

<p><strong>Status:</strong> <%= @avenger.alive? ? "Alive" : "Deceased" %></p>

<p><strong>Notes:</strong> <%= @avenger.notes %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avengerscc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Avengers Assemble!", root_url, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "New Avenger", new_avenger_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container">
    <% if flash.any? %>
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key %>"><%= message %></div>
      <% end %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>